# Generated by Django 5.2.7 on 2025-10-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_analyzer', '0003_remove_userprofile_dietary_preferences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='diet_type',
            field=models.CharField(choices=[('any', 'Any'), ('veg', 'Vegetarian'), ('nonveg', 'Non-Vegetarian')], default='any', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='activity_level',
            field=models.FloatField(blank=True, choices=[(1.2, 'Sedentary (little or no exercise)'), (1.375, 'Lightly active (light exercise/sports 1-3 days/week)'), (1.55, 'Moderately active (moderate exercise/sports 3-5 days/week)'), (1.725, 'Very active (hard exercise/sports 6-7 days a week)'), (1.9, 'Super active (very hard exercise/physical job)')], null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='allergies',
            field=models.TextField(blank=True, help_text='Comma-separated list, e.g., peanuts, shellfish, dairy'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, choices=[('lose', 'Weight Loss'), ('maintain', 'Weight Maintenance'), ('gain', 'Muscle Gain')], max_length=10, null=True),
        ),
    ]
