# Generated by Django 5.2.7 on 2026-07-15 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_analyzer', '0004_userprofile_diet_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='diet_diabetic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='diet_high_protein',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='diet_low_carb',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='diet_type',
            field=models.CharField(choices=[('any', 'Any'), ('veg', 'Vegetarian'), ('vegan', 'Vegan'), ('nonveg', 'Non-Vegetarian')], default='any', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='goal',
            field=models.CharField(blank=True, choices=[('lose', 'Weight Loss'), ('maintain', 'Weight Maintenance'), ('gain', 'Weight Gain'), ('muscle', 'Muscle Gain')], max_length=10, null=True),
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='food_analyzer.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DietRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('plan_data', models.JSONField()),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_recommendations', to='food_analyzer.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FoodDetectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='food_images/')),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('food_name', models.CharField(max_length=100)),
                ('quantity', models.IntegerField(default=1)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('calories', models.FloatField()),
                ('protein_g', models.FloatField()),
                ('carbs_g', models.FloatField()),
                ('fat_g', models.FloatField()),
                ('health_score', models.IntegerField(blank=True, null=True)),
                ('health_analysis', models.JSONField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_detections', to='food_analyzer.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='medical_reports/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('extracted_text', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('blood_sugar', models.FloatField(blank=True, null=True)),
                ('hba1c', models.FloatField(blank=True, null=True)),
                ('cholesterol', models.FloatField(blank=True, null=True)),
                ('ldl', models.FloatField(blank=True, null=True)),
                ('hdl', models.FloatField(blank=True, null=True)),
                ('vitamin_d', models.FloatField(blank=True, null=True)),
                ('vitamin_b12', models.FloatField(blank=True, null=True)),
                ('iron', models.FloatField(blank=True, null=True)),
                ('hemoglobin', models.FloatField(blank=True, null=True)),
                ('blood_pressure', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_reports', to='food_analyzer.userprofile')),
            ],
        ),
    ]
